window.AFTER_EVENTOS = [
  {
    id: "torneo-standard-14-08",
    titulo: "Torneo TCG Standard",
    categoria: "TCG",
    modalidad: "Competitivo",
    fecha: "2026-08-14",
    hora: "20:00",
    cuposTotales: 8,
    reservados: 5,
    precio: 4000,
    imagen: "assets/eventos/torneo-standard.jpg",
    resumen: "Torneo formato Standard con rondas suizas.",
    descripcion: "Una fecha competitiva para jugar, aprender y medirte con la comunidad. Se recomienda llegar 15 minutos antes.",
    incluye: ["Rondas suizas", "Premios para el Top", "Sorteo entre participantes"],
    destacado: true
  },
  {
    id: "noche-switch-15-08",
    titulo: "Noche de Switch",
    categoria: "Switch",
    modalidad: "Multijugador",
    fecha: "2026-08-15",
    hora: "18:00",
    cuposTotales: 8,
    reservados: 4,
    precio: 2500,
    imagen: "assets/eventos/noche-switch.jpg",
    resumen: "Mario Kart, Smash y juegos para compartir.",
    descripcion: "Una noche casual con rotación de juegos, desafíos amistosos y espacio para comer algo.",
    incluye: ["Consola y pantalla", "Rotación de juegos", "Desafíos casuales"],
    destacado: true
  },
  {
    id: "apertura-intercambio-18-08",
    titulo: "Apertura + Intercambio",
    categoria: "Casual",
    modalidad: "Comunidad",
    fecha: "2026-08-18",
    hora: "19:00",
    cuposTotales: 8,
    reservados: 2,
    precio: 2000,
    imagen: "assets/eventos/apertura-intercambio.jpg",
    resumen: "Abrimos sobres, intercambiamos y jugamos.",
    descripcion: "Traé tus cartas, tu binder o tu mazo. Ideal para conocer gente y pasar la tarde.",
    incluye: ["Mesa de intercambio", "Partidas casuales", "Zona de apertura"],
    destacado: true
  },
  {
    id: "encuentro-comunidad-22-08",
    titulo: "Encuentro de Comunidad",
    categoria: "Especial",
    modalidad: "Mixto",
    fecha: "2026-08-22",
    hora: "18:30",
    cuposTotales: 8,
    reservados: 1,
    precio: 0,
    imagen: "assets/eventos/encuentro-comunidad.jpg",
    resumen: "Una fecha abierta para conocer After TCG.",
    descripcion: "Juegos, demostraciones, espacio para conversar y conocer la propuesta del local.",
    incluye: ["Entrada sin cargo", "Actividades sorpresa", "Espacio de comunidad"],
    destacado: false
  }
];
